[notebook]
dir = "/Users/vberniex/Documents/vault"

# Note settings
[note]
default="Untitled"
# Note name format
filename="{{id}}-{{format-date now '%Y%m%d'}}-{{title}}"
extension="md"

# ID Note Format
id-charset="alphanum"
id-length=8
id-case="lower"

[templates]
paths = ["~/.config/zk/templates"]

[extra]
author="hxbr"

[tool]
editor="nvim"
shell="/bin/zsh"
pager="less -FIRX"
fzf-preview="bat -p --color always {-1}"
[format.markdown]
link-format = "[[{{metadata.id}}|{{title}}]]"

[lsp]

[lsp.diagnostics]
wiki-title="hint"
dead-link="error"

[lsp.completion]
note-label = "{{path}}"
note-filter-text = "{{title}} {{path}}"
note-detail = "{{filename-stem}}"

[filter]
recents="--sort created- --created-after 'last two weeks'"

[alias]
edlast = "zk edit --limit 1 --sort modified- $@"
bl = "zk list --link-to $@"
recent = "zk edit --sort created- --created-after 'last two weeks' --interactive"
lucky = "zk list --quiet --format full --sort random --limit 1"

daily = 'zk new --no-input "002-Journal/daily"'

inline = "zk list --quiet --format {{path}} --delimiter , $@"

ix = "zk edit --tag=index --interactive"

fleeting = "zk edit --tag=fleeting --interactive"

lit = "zk edit --tag=literature --interactive"

permanent = "zk edit --tag=permanent --interactive"

project = "zk edit --tag=project --interactive"

journal = "zk edit --tag=type/journal --interactive"

[group.daily]
paths = ["002-Journal/daily"]

[group.daily.note]
filename = "{{format-date now '%Y-%m-%d'}}"
extension = "md"
template = "daily.md"

