tap "daveshanley/vacuum"
tap "felixkratz/formulae"
tap "jstkdng/programs"
tap "koekeishiya/formulae"
tap "nikitabobko/tap"

# Packages 
# Text Packages
brew "gettext"
brew "bat"
brew "less"
brew "tectonic"

# System Packages
brew "btop"
brew "htop"

# Terminal Emulators & Multiplexers
cask "kitty"
brew "tmux"

# Shell Configurations
brew "bash"
brew "fish"
brew "zsh-autocomplete"
brew "zsh-autosuggestions"
brew "zsh-completions"
brew "zsh-syntax-highlighting"
brew "nushell"

# language interpreters
brew "python@3.13"

# Interesting packages
brew "bc"
brew "c10t"

# Image processers
brew "chafa"
brew "libsixel"
brew "imagemagick"
brew "jstkdng/programs/ueberzugpp"

# LSP, Linters and Code checkers
brew "ccls"
brew "bash-language-server"
brew "dotenv-linter"
brew "chezmoi"
brew "cppcheck"
brew "doxygen"
brew "luacheck"
brew "selene"
brew "ninja"
brew "stylua"
brew "prettierd"
brew "shellcheck"

# Sick packages
brew "cmatrix"
brew "cowsay"
brew "glow"
brew "fortune"
cask "whisky"
brew "lolcat"
brew "spotify_player"

# Docker Packages
brew "docker"
brew "docker-buildx"
brew "docker-compose"
brew "colima", restart_service: :changed

# Benchmark, Filesystem & Searching Packages
brew "fd"
brew "fzf"
brew "jq"
brew "lf"
brew "ripgrep"
brew "sk"
brew "hyperfine"
brew "json-glib"
brew "tree"

# Compilers & debuggers
brew "llvm"
brew "gcc"
brew "cmake"
brew "cmake-docs"
brew "gawk"
brew "clang-format"
brew "lld"
brew "nasm"

# Version Control Packages
brew "gh"
brew "git"
brew "glab"
brew "lazygit"

# Editors
brew "ghex"
brew "neovim"
brew "jupyterlab"

# Unit Testing
brew "cunit"

# Note Taking Packages
brew "zk"

# Language environments
brew "node"
brew "coreutils"
brew "ghostscript"
brew "git-lfs"
brew "gnu-sed"
brew "go"
brew "gtk+"
brew "gtk+3"

brew "lua-language-server"
brew "luarocks"
brew "meson"
brew "mpc"
brew "mpd", restart_service: :changed
brew "mpv"
brew "mupdf"
brew "ncdu"
brew "pipes-sh"
brew "pipx"
brew "pngpaste"
brew "podman"
brew "pyenv"
brew "qemu"
brew "qt"
brew "rust"
brew "rustup"
brew "vite"
brew "wget"
brew "xxh"
brew "yaml-language-server"
brew "yarn"
brew "daveshanley/vacuum/vacuum"
brew "felixkratz/formulae/sketchybar"

# Applications
cask "aerospace"
cask "font-monaspace-nerd-font"
cask "font-noto-sans-symbols-2"
cask "iterm2"
cask "metasploit"
cask "pycharm"
cask "skim"
cask "visual-studio-code"
cask "xquartz"

# Vscode and nvim-dap packages
vscode "adrianwilczynski.terminal-commands"
vscode "asvetliakov.vscode-neovim"
vscode "bierner.markdown-mermaid"
vscode "bpruitt-goddard.mermaid-markdown-syntax-highlighting"
vscode "dart-code.dart-code"
vscode "dsznajder.es7-react-js-snippets"
vscode "ecmel.vscode-html-css"
vscode "ekelley.midnight-synth"
vscode "github.copilot"
vscode "github.copilot-chat"
vscode "github.vscode-github-actions"
vscode "github.vscode-pull-request-github"
vscode "golang.go"
vscode "icrawl.discord-vscode"
vscode "mgmcdermott.vscode-language-babel"
vscode "ms-python.debugpy"
vscode "ms-python.python"
vscode "ms-python.vscode-pylance"
vscode "ms-toolsai.jupyter"
vscode "ms-toolsai.jupyter-keymap"
vscode "ms-toolsai.jupyter-renderers"
vscode "ms-toolsai.vscode-jupyter-cell-tags"
vscode "ms-toolsai.vscode-jupyter-slideshow"
vscode "ms-vscode-remote.remote-ssh"
vscode "ms-vscode-remote.remote-ssh-edit"
vscode "ms-vscode.cmake-tools"
vscode "ms-vscode.cpptools"
vscode "ms-vscode.cpptools-extension-pack"
vscode "ms-vscode.cpptools-themes"
vscode "ms-vscode.js-debug-nightly"
vscode "ms-vscode.makefile-tools"
vscode "ms-vscode.remote-explorer"
vscode "ms-vscode.remote-server"
vscode "ms-vscode.vscode-typescript-next"
vscode "ritwickdey.liveserver"
vscode "robbowen.synthwave-vscode"
vscode "shd101wyy.markdown-preview-enhanced"
vscode "vintharas.learn-vim"
vscode "vscodevim.vim"
vscode "vstirbu.vscode-mermaid-preview"
vscode "xabikos.javascriptsnippets"
