#!/bin/zsh
#===================================================================================
#  DESCRIPTION:  Laaaa la la la, wait till I get my money right
#       AUTHOR:  I forgor
#
#  ███████╗███████╗██╗  ██╗██████╗  ██████╗
#  ╚══███╔╝██╔════╝██║  ██║██╔══██╗██╔════╝
#    ███╔╝ ███████╗███████║██████╔╝██║     
#   ███╔╝  ╚════██║██╔══██║██╔══██╗██║     
#  ███████╗███████║██║  ██║██║  ██║╚██████╗
#  ╚══════╝╚══════╝╚═╝  ╚═╝╚═╝  ╚═╝ ╚═════╝
#
#===================================================================================

# Initialize ohmyzsh

ZSH_THEME="spaceship"

plugins=(
	git
	macos
	jsontools
)

# Environmental variables

if [ -f ~/.env ]; then
    source ~/.env
fi

# preferred editor for local and remote sessions
if [[ -n $SSH_CONNECTION ]]; then
  export EDITOR='nvim'
else
  export EDITOR='vim'
fi

if [ -z "$TMUX" ] && [ "$TERM_PROGRAM" = "ghostty" ]; then
  tmux attach -t main || tmux new -s main || echo "Failed to start tmux"
fi

# Zsh-autocomplete settings
source /opt/homebrew/share/zsh-autocomplete/zsh-autocomplete.plugin.zsh

# Lazygit configuration
# CD to working directory
lg()
{
    export LAZYGIT_NEW_DIR_FILE=~/.lazygit/newdir

    lazygit "$@"

    if [ -f $LAZYGIT_NEW_DIR_FILE ]; then
            cd "$(cat $LAZYGIT_NEW_DIR_FILE)"
            rm -f $LAZYGIT_NEW_DIR_FILE > /dev/null
    fi
}

export ARCHFLAGS="-arch $(uname -m)"


alias v="nvim"
alias sp="spotify_player"
alias lzg="lazygit"
alias man='MANPAGER="less -XNR --use-color -Dd+y -Du+208 -DN+r" man' 
alias vault='cd ~/Documents/vault'
alias core='cd ~/Documents/projects/The-Core-Dump'
alias config='cd ~/.config'
alias lab='cd ~/Documents/projects/Lab'
alias ls="ls --color=auto"
alias projects="cd ~/Documents/projects"

# Lf configurations
# to save the current directory
if type lf &> /dev/null; then
	# set up icons
	LF_ICONS=$(sed -e '/^[ \t]*#/d' \
		-e '/^[ \t]*$/d' \
		-e 's/[ \t]\+/=/g' \
		-e 's/$/ /' \
		"$HOME/.config/lf/icons")


	# Setup lfcd
	LFCD="$HOME/.config/lf/scripts/lfcd.sh"
	if [ -f "$LFCD" ]; then
		source "$LFCD"
		bindkey -s "^o" "lfcd\n"  # set up key-binding for zsh
		alias lf="lfcd"  # overwrite lf with lfcd
	fi
fi
	
#zsh-syntax-highlighing
source /opt/homebrew/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh

source $ZSH/oh-my-zsh.sh
